### ISSUE TITLE
Containers from different environments can see each other

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/Subutai-snappy#16]
If we have several environments on one resource host, containers from these environments can ping each other. This is unacceptable and should be fixed.

**Comment by almaz2014** [comment]
#!/bin/bash

#README
#divide_flows.sh {add|del}  GW_NAME GW_IP
#EXAMPLE:
#divide_flows.sh add gw-101 192.168.2.1
#divide_flows.sh del gw-101



#function set_rules( GW_NAME,  GW_IP )
#Apply  openflow rules to wan interface to block traffic from another NET
#Example:
#   set_rules gw-100 192.168.1.1
function set_rules() {

if [ -z $1 ]; then 
     echo "Set GW_NAME"
     exit 0
fi

if [ -z $2 ]; then 
     echo "Set GW_IP"
     exit 0
fi


GW_NAME=$1
GW_IP=$2

declare -a IPARR
IPARR=(`echo ${GW_IP//./ }`)
GW_NET="${IPARR[0]}.${IPARR[1]}.${IPARR[2]}.0"
echo "GW_NET=$GW_NET"
OF_PORT=$(sudo ovs-ofctl show wan | grep $GW_NAME | awk -F"(" '{print $1}' | tr -d "[:space:]")
sudo ovs-ofctl add-flow wan "priority=2600,in_port=$OF_PORT,ip,nw_src=$GW_IP actions=normal"
sudo ovs-ofctl add-flow wan "priority=2600,in_port=$OF_PORT,ip,nw_src=$GW_NET/24,nw_dst=$GW_NET/24 actions=normal"
sudo ovs-ofctl add-flow wan "priority=2500,in_port=$OF_PORT,ip,nw_src=10.10.10.0/24 actions=drop"
sudo ovs-ofctl add-flow wan "priority=2500,in_port=$OF_PORT,ip,nw_src=10.0.0.0/8 actions=drop"
sudo ovs-ofctl add-flow wan "priority=2500,in_port=$OF_PORT,ip,nw_src=172.16.0.0/12 actions=drop"
sudo ovs-ofctl add-flow wan "priority=2500,in_port=$OF_PORT,ip,nw_src=192.168.0.0/16 actions=drop"
}


#function del_rules ( GW_NAME )
# Deletes openflow rules from wan interface for given name of gateway
#Example :
#   del_rules gw-100
function del_rules() {
if [ -z $1 ]; then 
     echo "Set GW_NAME"
     exit 0
fi

GW_NAME=$1
OF_PORT=$(sudo ovs-ofctl show wan | grep $GW_NAME | awk -F"(" '{print $1}' | tr -d "[:space:]")
sudo ovs-ofctl del-flows wan "in_port=$OF_PORT"
}

#Examples:
 
#set_rules gw-100 192.168.1.1
#set_rules gw-101 192.168.2.1
#set_rules gw-105 192.168.4.1

#del_rules gw-100
#del_rules gw-101
#del_rules gw-105



case "$1" in
        add)
            set_rules $2 $3
            ;;
        del)
            del_rules $2
            ;;
        *)
            echo $"Usage: $0 {add|del}  GW_NAME GW_IP"
            echo $"EXAMPLES:"
            echo $"   divide_flows.sh add gw-101 192.168.2.1"
            echo $"   divide_flows.sh del gw-101"


            exit 1
esac

**Comment by almaz2014** [comment]
created branch git clone -b openflow https://github.com/subutai-io/Subutai-snappy.git
